global:
  scrape_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana-strads:3000']

  - job_name: 'strands_dashboard'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['strands-dashboard:8000']

  - job_name: 'strands_seo_analyzer'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['strands-seo-analyzer:8001']
