global:
  scrape_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager-strads:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana-strads:3000']

  - job_name: 'strands_dashboard'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['strands-dashboard:8000']

  - job_name: 'strands_seo_analyzer'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['strands-seo-analyzer:8001']
  - job_name: 'trigger_alert'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8888']
    scrape_interval: 5s