name: strands-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - flake8
  - pytest
  - pytest-asyncio
  - pip:
      - fastapi
      - uvicorn
      - pydantic>=2.0.0
      - neo4j
      - qdrant-client
      - python-dotenv
      - httpx  # Essencial para testar o FastAPI com pytest
