name: Python Package using Conda

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: strands-env # Nome do env no seu environment.yml
        environment-file: environment.yml
        python-version: '3.10'
        auto-activate-base: false
        use-mamba: true # O Mamba é muito mais rápido que o Conda para resolver dependências

    - name: Lint with flake8
      shell: bash -el {0} # O parâmetro -el garante que o conda esteja ativo neste step
      run: |
        # Recomendação: adicione flake8 ao seu environment.yml
        conda install -y flake8 
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      shell: bash -el {0}
      run: |
        # Recomendação: adicione pytest ao seu environment.yml
        conda install -y pytest
        pytest
